# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "OFF")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "OFF")
SET(CPACK_BINARY_IFW "OFF")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "OFF")
SET(CPACK_BINARY_PACKAGEMAKER "OFF")
SET(CPACK_BINARY_PRODUCTBUILD "OFF")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TXZ "OFF")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_BUILD_SOURCE_DIRS "/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib/fmt-4.0.0;/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "STGZ;TGZ")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib;FMT;ALL;/")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib/fmt-4.0.0/support/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "fmt 4.0.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "fmt 4.0.0")
SET(CPACK_OUTPUT_CONFIG_FILE "/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/opt/local/share/cmake-3.7/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "FMT built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "fmt-4.0.0-Darwin")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "fmt 4.0.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "fmt 4.0.0")
SET(CPACK_PACKAGE_NAME "fmt")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "4.0.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "4")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "/opt/local/share/cmake-3.7/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib/fmt-4.0.0/README.rst")
SET(CPACK_RESOURCE_FILE_WELCOME "/opt/local/share/cmake-3.7/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "bin/$;bin//;/_CPack_Packages$;/_CPack_Packages/;/doc/doxyxml$;/doc/doxyxml/;virtualenv$;virtualenv/;/Testing$;/Testing/;/install_manifest[.]txt$;/install_manifest[.]txt/;.*~$;.*~/;.*[.]a$;.*[.]a/;.*[.]so.*$;.*[.]so.*/;.*[.]zip$;.*[.]zip/;cmake_install[.]cmake$;cmake_install[.]cmake/;CPack.*[.]cmake$;CPack.*[.]cmake/;fmt-.*[.]cmake$;fmt-.*[.]cmake/;CTestTestfile[.]cmake$;CTestTestfile[.]cmake/;CMakeCache[.]txt$;CMakeCache[.]txt/;CMakeFiles$;CMakeFiles/;Makefile$;Makefile/;run-msbuild[.]bat$;run-msbuild[.]bat/;/.git;/breathe;/format-benchmark;sphinx/;.buildinfo;.doctrees")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "fmt-4.0.0")
SET(CPACK_SOURCE_RPM "")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_SYSTEM_NAME "Darwin")
SET(CPACK_TOPLEVEL_TAG "Darwin")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/Users/denysmelnychenko/Documents/C++/MOOP/atm/atm/lib/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
